### ISSUE TITLE
Why not let the bootloader inject Lilu and NSU?

### ISSUE THREAD

**Issue by PMheart** [Austere-J/NightShiftUnlocker#1]
Hello FireWolf

According to vit9696's instructions, it's better to load everything related to Lilu via InjectKext, otherwise it may fail.

Also, why not use SYSLOG, DBGLOG for logging from Lilu, it's just a simple macro though...
As for os version detecting, I guess Lilu has already contained it and thus we don't really need to do something like now what you've done?
BTW. After declaring the "ret" instruction you don't need to NOP out the next bytes. (I'm mentioning this one: https://github.com/Austere-J/NightShiftUnlocker/blob/master/NightShiftUnlocker/Patches.cpp#L41)

**Comment by 0xFireWolf** [comment]
Hello. Thanks for your question.

> According to vit9696's instructions, it's better to load everything related to Lilu via InjectKext, otherwise it may fail.

Well, I always install 3rd-party drivers to `/Library/Extensions/` as suggested by Apple. It works like a charm.

Besides, since NightShiftUnlocker supports both Genuine Macs and Hackintoshes, and real Macs don't have the Clover bootloader, I think it's better to install them to /L/E.

> Also, why not use SYSLOG, DBGLOG for logging from Lilu, it's just a simple macro though...

Yes, I am aware of those macros. I think it's just personal preferences.

> As for os version detecting, I guess Lilu has already contained it and thus we don't really need to do something like now what you've done?

I noticed that Lilu has an API to get the current kernel major version, but I didn't find any APIs provided by Lilu to get the current OS version. 
Note that it is not accurate to detect the OS version by the kernel version because some OS releases share the same kernel version.
Although it is better for me to provide a generic binary patch, I am still trying to find a better way to get the OS info or hook and route the function implementation.

Thank you for your question and suggestion.
If you have any other questions, don't hesitate to contact me.

Cheers,
FireWolf

**Comment by PMheart** [comment]
Hi.
BTW, PCBeta is now available to access, and why not post this repo there? ;)

Yes though, Lilu is a patcher, which should be loaded as early as possible, and Clover's InjectKext will give us a hand. Also. Clover uses XNU code to inject kexts if I remember correctly, so don't worry about that, it's reasonably reliable. I myself still keeping everything in /L/E though... (I think Clover's algorithm is still somewhat not good, but it's definitely another story) And anyway. Lilu can be firstly developed which targets at no filesystem modifications as vit9696 mentioned in his AppleALC thread.
As for real Macs. Yeah, we have to install them in /L/E cuz we don't have a better solution for now.
Well, Lilu is currently lack of minor version detecting indeed and I discussed this with vit9696 a couple of time ago, nonetheless unfortunately it seemed that Vit didn't really want to add this due to some reasons...

And about the exact patch that will be applied to CoreBrightness, from what I've gotten, what about using this one instead? (Less bytes, less trouble)

> _CBU_IsNightShiftSupported:
000000000001acb5	55 	pushq	%rbp
000000000001acb6	48 89 e5 	movq	%rsp, %rbp
000000000001acb9	41 57 	pushq	%r15
000000000001acbb	41 56 	pushq	%r14
000000000001acbd	41 55 	pushq	%r13
000000000001acbf	41 54 	pushq	%r12
000000000001acc1	53 	pushq	%rbx
000000000001acc2	48 83 ec 18 	subq	$0x18, %rsp
000000000001acc6	bf 01 00 00 00 	movl	$0x1, %edi
000000000001accb	e8 c4 15 00 00 	callq	0x1c294 ## symbol stub for: _ASI_CopyComputerModelName
000000000001acd0	48 89 45 d0 	movq	%rax, -0x30(%rbp)
000000000001acd4	31 db 	xorl	%ebx, %ebx
000000000001acd6	48 85 c0 	testq	%rax, %rax
000000000001acd9	41 bc 00 00 00 00 	movl	$0x0, %r12d
000000000001acdf	0f 84 c1 00 00 00 	je	0x1ada6          // jmp this je instruction

And the patch will be:
`41 bc 00 00 00 00 0f 84 c1 00 00 00` -> `41 bc 00 00 00 00 90 e9 c1 00 00 00`

Running
`perl -le "print scalar grep /\x41\xbc\x00\x00\x00\x00\x0f\x84\xc1\x00\x00\x00/, <>;" /System/Library/PrivateFrameworks/CoreBrightness.framework/Versions/A/CoreBrightness`
It returns `$count`, which is `1` here, therefore we'll just patch it once.

PMheart

**Comment by 0xFireWolf** [comment]
Your patch is incorrect.

> 0x1acd9: movl $0x0, %r12d
> 0x1acdf: jmp 0x1ada6 // ORG: je 0x1ada6
> 0x1ada6: movb %r12b, %al

%r12 is used to store the return value. Your patch will let the function return 0.

There are various way to patch the binary. As long as the function return `true`, we are good.

**Comment by PMheart** [comment]
Why? After calling `_ASI_CopyComputerModelName()` the return value should be an integer, and `0` is fine, isn't it? Great. To be honest, I'm not sure since I'm not very familiar with disassembly.

In any case, a nice Lilu plugin and, issue closed :)
