### ISSUE TITLE
安裝後無法調整屏幕亮度。

### ISSUE THREAD

**Issue by PeterWan816** [Austere-J/NightShiftUnlocker#10]
安裝後無法調整屏幕亮度。

**Comment by 0xFireWolf** [comment]
你的机器是白苹果 MacBook Pro 2010 年中款？

用了本补丁后 才出现的亮度无法调节以及睡眠唤醒失败的问题？

把补丁删除后 并且重建内核以及动态链接库缓存后 是否存在此问题？

**Comment by PeterWan816** [comment]
我很抱歉，這個問題與你的script無關，因為我無法通過卸載你的script來修復它。 我安裝你的腳本後我得到了night shift...我重新安裝了MacOS並通過patcher得到了night shift。 謝謝你的幫助和抱歉。
